import "server-only";

import * as documents from "@/lib/repositories/documents";
import {
  generatedDocumentToMarkdown,
  type GeneratedCoverLetter,
  type GeneratedResume,
} from "@/lib/generated-documents";
import type { JDAnalysis } from "@/lib/job-analysis";
import type { InterviewPrep } from "@/lib/job-ai-generation";
import { DEMO_PERSONA, DEMO_SIGNATURE_STORY, personaResume } from "@/lib/demo-persona";

/**
 * Canned AI output for the public demo account.
 *
 * The demo has full CRUD but never calls Anthropic, so every generation type
 * needs a fixture. Fixtures are interpolated with the real job's company and
 * role so the output reads as genuinely tailored rather than obviously static,
 * and the structured-document types are persisted as real Document records so
 * DOCX export works from the demo exactly as it does for a real user.
 */

const DEMO_MODEL = "claude-sonnet-4-5 (demo fixture)";

/**
 * Appended to free-text demo output so the label sits with the content itself,
 * not only in the page banner. A visitor who copies the text, or who lands
 * straight on a generated document, still sees what it is.
 */
export const DEMO_OUTPUT_NOTE =
  "*Demo output: written in advance, not generated by Claude. Sign up to generate this from your own resume and job description.*";


export type DemoJob = {
  _id: string;
  company: string;
  role: string;
  location?: string | null;
};

const { name: PERSONA_NAME, firstName: PERSONA_FIRST_NAME } = DEMO_PERSONA;
const YEARS = DEMO_PERSONA.yearsExperience;
const CURRENT_EMPLOYER = DEMO_PERSONA.experience[0].company;

// ---------------------------------------------------------------------------
// Structured documents (resume / cover letter)
// ---------------------------------------------------------------------------

function demoResume(job: DemoJob): GeneratedResume {
  return {
    ...personaResume(),
    summary: `Full stack engineer with ${YEARS} years building customer-facing web products, targeting the ${job.role} role at ${job.company}. Depth in TypeScript, React and Node, with a habit of measuring before changing anything and owning features from the database through to the interface.`,
  };
}

function demoCoverLetter(job: DemoJob): GeneratedCoverLetter {
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return {
    kind: "cover_letter",
    name: PERSONA_NAME,
    contact: { ...DEMO_PERSONA.contact },
    date: today,
    recipient: "Hiring Team",
    company: job.company,
    role: job.role,
    bodyParagraphs: [
      `I am applying for the ${job.role} role at ${job.company}. What drew me to the posting was the emphasis on owning features end to end, because that is the kind of work I have sought out for most of the last ${YEARS} years.`,
      `At ${CURRENT_EMPLOYER} I led the rebuild of our checkout. Before writing any code I instrumented the existing flow and found that most of the delay came from three blocking requests, not from the interface. Fixing those first took load time from 3.8 seconds to 1.2 and lifted completed orders by 9%. I mention it because it is a fair sample of how I work: measure, fix the thing that matters, then polish.`,
      `Before that I spent three years at Harbor Health building appointment booking for around 40 clinics, including making it work offline in buildings with poor signal. I enjoy the unglamorous parts of product work, and I tend to be the person who wants the data model right before the interface.`,
      `I would welcome the chance to talk about the ${job.role} role and what the team is working on.`,
    ],
    closing: null,
    signoff: `Best regards,\n${PERSONA_NAME}`,
  };
}

// ---------------------------------------------------------------------------
// Analysis and prep
// ---------------------------------------------------------------------------

function demoJDAnalysis(job: DemoJob): JDAnalysis {
  return {
    summary: `A senior-leaning full stack role at ${job.company} building product surfaces end to end. The posting weights breadth (owning a feature from data model to interface) over narrow specialisation, and asks for evidence of shipping rather than familiarity with a stack.`,
    seniorityLevel: "senior",
    requiredSkills: [
      "TypeScript",
      "React",
      "Node.js",
      "Relational data modelling",
      "REST API design",
      "Automated testing",
    ],
    niceToHaves: [
      "Server-side rendering experience",
      "Search or recommendations work",
      "Observability and on-call ownership",
      "Mentoring or technical leadership",
    ],
    keywordsForResume: [
      "full stack",
      "TypeScript",
      "React",
      "Next.js",
      "Node.js",
      "data modelling",
      "end to end ownership",
      "performance",
      "code review",
      "testing",
    ],
    interviewLikelyFocus: [
      "System design with an emphasis on data modelling trade-offs",
      "A practical coding round weighted toward readable, well-factored code",
      "Debugging a production issue under time pressure",
      "Behavioural questions about ownership and disagreement",
    ],
    redFlags: [
      `The posting does not name a compensation band, so raise it early rather than late.`,
      `"Wears many hats" appears alongside a small team size, which often means on-call and support duty are part of the role. Worth asking about directly.`,
    ],
  };
}

function demoInterviewPrep(job: DemoJob): InterviewPrep {
  return {
    behavioral: [
      {
        question: "Tell me about a time you disagreed with a technical decision.",
        hint: "Lead with the questions you asked before asserting anything, and say explicitly that you offered to support the other approach if the evidence went against you.",
      },
      {
        question: "Describe a project you owned end to end.",
        hint: DEMO_SIGNATURE_STORY.interviewHint,
      },
      {
        question: "Tell me about a time you made a mistake in production.",
        hint: "Pick one with real consequence and be specific about what you changed structurally afterwards, not just what you fixed. A story with no cost reads as evasive.",
      },
    ],
    technical: [
      {
        question: `How would you design the data model for ${job.company}'s core product?`,
        hint: "Clarify access patterns before writing anything down. Say out loud which queries you are optimising for and what you are willing to make slower.",
      },
      {
        question: "Walk me through how you would debug a slow page.",
        hint: "Measure before hypothesising. Separate network, server and rendering time, then talk about how you would confirm the fix actually moved the number users feel.",
      },
      {
        question: "How would you make search results feel more relevant?",
        hint: "Start with how you would measure relevance (click-through, search-to-cart), then cover synonyms, typo tolerance and boosting before reaching for anything exotic.",
      },
    ],
    roleSpecific: [
      {
        question: `Why the ${job.role} role specifically, rather than a pure frontend or pure backend one?`,
        hint: "Answer with a concrete preference rather than a claim of flexibility: you want the data model and the interface in the same head because the interesting bugs live between them.",
      },
      {
        question: "How do you decide what to test?",
        hint: "Payment paths, permission checks and anything customers make decisions from. Say explicitly that you do not chase a coverage number and why.",
      },
    ],
    cultureFit: [
      {
        question: "How do you handle competing priorities?",
        hint: "Show a decision procedure, not a personality trait. Who you escalate to and how quickly matters more than saying you stay calm.",
      },
      {
        question: "What kind of code review do you like to receive?",
        hint: "Specific and early. Mention that you would rather be told the design is wrong on day one than have the implementation praised on day five.",
      },
    ],
    questionsToAskThem: [
      "What does the first ninety days look like for whoever takes this role?",
      "Where does the current architecture hurt most, and what would you change with a free month?",
      "How do decisions get made when engineering and product disagree?",
      "What does on-call look like, and how often does it actually page?",
      `What would make you say in six months that this ${job.role} hire went really well?`,
    ],
  };
}

// ---------------------------------------------------------------------------
// Outreach
// ---------------------------------------------------------------------------

const OUTREACH_FIXTURES: Record<string, (job: DemoJob) => string> = {
  linkedin_note: (job) =>
    `Hi - I have just applied for the ${job.role} role at ${job.company}. I have spent the last few years on checkout and search work that lines up closely with what the posting describes, and I would welcome the chance to connect.`,

  linkedin_dm: (job) =>
    `Hi,\n\nI applied for the ${job.role} role last week and wanted to introduce myself directly.\n\nThe short version: ${YEARS} years of full stack work, most recently ${DEMO_SIGNATURE_STORY.short}. The posting's emphasis on end-to-end ownership is what made me apply, more than the stack.\n\nHappy to send more detail if useful, and equally happy if the timing is not right.\n\nBest,\n${PERSONA_FIRST_NAME}`,

  followup_email: (job) =>
    `Subject: Following up on the ${job.role} application\n\nHi,\n\nI applied for the ${job.role} role at ${job.company} a couple of weeks ago and wanted to check in briefly in case my application had not surfaced.\n\nThe posting mentions improving conversion on key flows, which is close to what I have been doing at ${CURRENT_EMPLOYER}: ${DEMO_SIGNATURE_STORY.short}. Happy to walk through it if it is relevant.\n\nStill interested, and I appreciate you taking the time.\n\nBest,\n${PERSONA_NAME}`,

  thankyou_email: (job) =>
    `Subject: Thank you\n\nHi,\n\nThank you for the time today. I enjoyed the conversation, particularly the discussion about where the product is growing fastest.\n\nOne thing I did not say well: when you asked how I would approach the redesign, I jumped to the mechanics. The part I should have led with is that I would ship it behind a flag to a small share of traffic first and compare the numbers, because on a flow customers pay through, being briefly slow is survivable and being briefly wrong is not.\n\nThanks again. I would be glad to keep talking about the ${job.role} role.\n\nBest,\n${PERSONA_FIRST_NAME}`,

  linkedin_followup_dm: (job) =>
    `Hi - following up on my note about the ${job.role} role. I know inboxes are busy, so no problem at all if the timing is not right or the search has moved on. If it would help to see how I think rather than read about it, I am happy to send a short write-up of a recent project. Either way, thanks.`,

  cold_email: (job) =>
    `Subject: Full stack engineer, interested in ${job.company}\n\nHi,\n\nI do not think you have an open ${job.role} posting right now, so this is speculative.\n\nI am a full stack engineer with ${YEARS} years of experience, most recently at ${CURRENT_EMPLOYER}, where I led a checkout rebuild. Before touching the interface I measured the existing flow and found most of the delay came from three blocking requests. Fixing those took load time from 3.8s to 1.2s and lifted completed orders by 9%.\n\nI am reaching out to ${job.company} specifically because the problems you are working on look close to that. If there is nothing now, I would still value being on your radar.\n\nBest,\n${PERSONA_NAME}`,

  checkin_email: (job) =>
    `Subject: Checking in\n\nHi,\n\nIt has been a few weeks since we spoke about the ${job.role} role, so I wanted to check in without being a nuisance.\n\nNothing has changed on my end: still interested, still available. If the role is on hold or has gone to someone else, I would genuinely rather know than keep wondering, and it would not change my view of the conversation we had.\n\nBest,\n${PERSONA_FIRST_NAME}`,

  salary_negotiation: (job) =>
    `Subject: ${job.role} offer\n\nHi,\n\nThank you for the offer. I want to say clearly up front that I want to work at ${job.company} and I expect us to land this.\n\nOn compensation: the base is below where I need to be. Based on the level of the role and what I have seen for comparable senior full stack positions, I am looking for a base of $185,000. I have another offer at $178,000 that I am not trying to leverage so much as be transparent about, because I would rather take this role at a fair number than the other one.\n\nIf base is constrained, I am open to discussing the equity or the signing component instead. What I care about is the total landing somewhere defensible.\n\nHappy to talk it through live if that is easier.\n\nBest,\n${PERSONA_FIRST_NAME}`,
};

// ---------------------------------------------------------------------------
// Entry points
// ---------------------------------------------------------------------------

export function demoOutreach(type: string, job: DemoJob): string {
  const build = OUTREACH_FIXTURES[type];
  if (build) return `${build(job)}\n\n${DEMO_OUTPUT_NOTE}`;
  return `No demo fixture exists for the "${type}" generator yet.\n\n${DEMO_OUTPUT_NOTE}`;
}

export function demoAnalysis(job: DemoJob): JDAnalysis {
  return demoJDAnalysis(job);
}

export function demoPrep(job: DemoJob): InterviewPrep {
  return demoInterviewPrep(job);
}

/**
 * Builds and persists a demo resume or cover letter. Writing a real Document
 * record keeps the demo honest end to end: the export button downloads a DOCX
 * built by the same pipeline a paying user would hit.
 */
export async function demoStructuredDocument(
  userId: string,
  job: DemoJob,
  type: "resume" | "cover_letter"
): Promise<{ documentId: string; content: string; structuredContent: GeneratedResume | GeneratedCoverLetter }> {
  const structuredContent =
    type === "resume" ? demoResume(job) : demoCoverLetter(job);
  // Note goes on the rendered markdown only. structuredContent stays clean so
  // the exported DOCX and LaTeX carry no demo boilerplate.
  const content = `${generatedDocumentToMarkdown(structuredContent)}\n\n${DEMO_OUTPUT_NOTE}`;

  const saved = await documents.upsert(userId, {
    jobId: job._id,
    type,
    content,
    structuredContent: structuredContent as unknown as Record<string, unknown>,
    aiModel: DEMO_MODEL,
    inputTokens: 0,
    outputTokens: 0,
  });

  return { documentId: saved._id, content, structuredContent };
}

// ---------------------------------------------------------------------------
// Fixtures for the standalone AI routes
//
// These live outside generateForJob(), so each needs its own fixture. The
// metering layer refuses demo calls outright (see assertNotDemoUser), which
// means a route added without a fixture fails loudly rather than billing.
// ---------------------------------------------------------------------------

export type DemoParsedJob = {
  company: string | null;
  role: string | null;
  location: string | null;
  salary: string | null;
  description: string | null;
};

export function demoParsedJob(): DemoParsedJob {
  return {
    company: "Example Corp",
    role: "Senior Full Stack Engineer",
    location: "Remote (US)",
    salary: "$180k - $215k",
    description:
      "This is demo output. Quick import normally sends your pasted job posting to Claude, which extracts the company, role, location, salary and a cleaned-up description. The demo account returns this fixed example instead, so nothing you paste is sent anywhere. Sign up with your own account to parse real postings.",
  };
}
