import "server-only";

import * as documents from "@/lib/repositories/documents";
import {
  generatedDocumentToMarkdown,
  type GeneratedCoverLetter,
  type GeneratedResume,
} from "@/lib/generated-documents";
import type { JDAnalysis } from "@/lib/job-analysis";
import type { InterviewPrep } from "@/lib/job-ai-generation";

/**
 * Canned AI output for the public demo account.
 *
 * The demo has full CRUD but never calls Anthropic, so every generation type
 * needs a fixture. Fixtures are interpolated with the real job's company and
 * role so the output reads as genuinely tailored rather than obviously static,
 * and the structured-document types are persisted as real Document records so
 * DOCX export works from the demo exactly as it does for a real user.
 */

const DEMO_MODEL = "claude-sonnet-4-5 (demo fixture)";

/**
 * Appended to free-text demo output so the label sits with the content itself,
 * not only in the page banner. A visitor who copies the text, or who lands
 * straight on a generated document, still sees what it is.
 */
export const DEMO_OUTPUT_NOTE =
  "*Demo output: written in advance, not generated by Claude. Sign up to generate this from your own resume and job description.*";


export type DemoJob = {
  _id: string;
  company: string;
  role: string;
  location?: string | null;
};

const DEMO_CONTACT = {
  location: "San Francisco, CA",
  phone: "+1 (555) 014-2277",
  email: "alex.morgan@example.com",
  linkedin: "linkedin.com/in/example",
  github: "github.com/example",
  website: null,
  workRights: null,
};

// ---------------------------------------------------------------------------
// Structured documents (resume / cover letter)
// ---------------------------------------------------------------------------

function demoResume(job: DemoJob): GeneratedResume {
  return {
    kind: "resume",
    name: "Alex Morgan",
    contact: DEMO_CONTACT,
    summary: `Full stack engineer with 7 years building and operating production web applications, targeting the ${job.role} role at ${job.company}. Depth in TypeScript, React and Node, with a track record of owning features from data model through to interface.`,
    skills: [
      {
        category: "Languages",
        items: ["TypeScript", "JavaScript", "Python", "SQL"],
      },
      {
        category: "Frontend",
        items: ["React", "Next.js", "Server Components", "Tailwind CSS"],
      },
      {
        category: "Backend",
        items: ["Node.js", "PostgreSQL", "MongoDB", "Redis", "REST APIs"],
      },
      {
        category: "Infrastructure",
        items: ["AWS", "Docker", "CI/CD", "Observability"],
      },
    ],
    experience: [
      {
        jobTitle: "Senior Software Engineer",
        company: "Meridian Labs",
        dateRange: "2021 - Present",
        subtitle: "San Francisco, CA",
        bullets: [
          "Led the migration of a 200,000-line React application to server-side rendering, cutting median time to interactive from 4.1s to 1.3s and shrinking the client bundle by 40%.",
          "Designed the billing and metering subsystem handling roughly 40,000 priced events per day, including the concurrency controls that keep spend limits correct under parallel load.",
          "Took the codebase from no automated coverage to a deterministic suite running on every pull request, reducing regressions per release by roughly 80%.",
          "Mentored four engineers, two of whom were promoted within eighteen months.",
        ],
      },
      {
        jobTitle: "Software Engineer",
        company: "Northwind Systems",
        dateRange: "2018 - 2021",
        subtitle: "Remote",
        bullets: [
          "Built the customer-facing analytics dashboard used by roughly 8,000 accounts.",
          "Replaced a nightly batch pipeline with an incremental one, reducing data latency from 18 hours to under 5 minutes with zero incorrect intermediate states.",
          "Owned on-call for the ingestion service and drove a 60% reduction in paging volume.",
        ],
      },
      {
        jobTitle: "Junior Developer",
        company: "Cobalt Interactive",
        dateRange: "2017 - 2018",
        subtitle: "Portland, OR",
        bullets: [
          "Shipped features across a Rails monolith and a React frontend.",
        ],
      },
    ],
    projects: [
      {
        name: "Job Hunt",
        techStack: "Next.js, TypeScript, MongoDB, Claude API",
        bullets: [
          "Full stack application tracker with AI-assisted document generation and USD-metered spend controls.",
          "Implemented atomic reserve-then-reconcile budgeting after finding a check-then-act race that let parallel requests exceed the cap.",
        ],
      },
    ],
    education: [
      {
        degree: "BSc Computer Science",
        school: "University of Oregon",
        gradDate: "2017",
        notes: null,
      },
    ],
    certifications: [],
    footer: null,
  };
}

function demoCoverLetter(job: DemoJob): GeneratedCoverLetter {
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return {
    kind: "cover_letter",
    name: "Alex Morgan",
    contact: DEMO_CONTACT,
    date: today,
    recipient: "Hiring Team",
    company: job.company,
    role: job.role,
    bodyParagraphs: [
      `I am applying for the ${job.role} role at ${job.company}. What drew me to the posting was the emphasis on owning features end to end, because that is the shape of work I have sought out for most of the last seven years.`,
      `At Meridian Labs I own a metered generation pipeline from the data model through to the interface. The part I am most proud of is unglamorous: I found that our spend limits were enforced with a check-then-act sequence, so twenty parallel requests all read the same stale total and all passed. I reproduced it with a test, replaced it with an atomic conditional update, and the reproduction now guards the invariant on every change. I mention it because it is a fair sample of how I work.`,
      `The wider context is seven years shipping production web applications in TypeScript and React. I led the migration of a 200,000-line application to server-side rendering, taking median time to interactive from 4.1 seconds to 1.3, and I took a codebase from no automated tests to a suite that runs on every pull request. I tend to be the person who wants the data model right before the interface.`,
      `I would welcome the chance to talk about the ${job.role} role and what the team is working on.`,
    ],
    closing: null,
    signoff: "Best regards,\nAlex Morgan",
  };
}

// ---------------------------------------------------------------------------
// Analysis and prep
// ---------------------------------------------------------------------------

function demoJDAnalysis(job: DemoJob): JDAnalysis {
  return {
    summary: `A senior-leaning full stack role at ${job.company} building product surfaces end to end. The posting weights breadth (owning a feature from data model to interface) over narrow specialisation, and asks for evidence of shipping rather than familiarity with a stack.`,
    seniorityLevel: "senior",
    requiredSkills: [
      "TypeScript",
      "React",
      "Node.js",
      "Relational or document data modelling",
      "REST API design",
      "Automated testing",
    ],
    niceToHaves: [
      "Server-side rendering experience",
      "LLM API integration",
      "Observability and on-call ownership",
      "Mentoring or technical leadership",
    ],
    keywordsForResume: [
      "full stack",
      "TypeScript",
      "React",
      "Next.js",
      "Node.js",
      "data modelling",
      "end to end ownership",
      "production systems",
      "code review",
      "testing",
    ],
    interviewLikelyFocus: [
      "System design with an emphasis on data modelling trade-offs",
      "A practical coding round weighted toward readable, well-factored code",
      "Debugging a production issue under time pressure",
      "Behavioural questions about ownership and disagreement",
    ],
    redFlags: [
      `The posting does not name a compensation band, so raise it early rather than late.`,
      `"Wears many hats" appears alongside a small team size, which often means on-call and support duty are part of the role. Worth asking about directly.`,
    ],
  };
}

function demoInterviewPrep(job: DemoJob): InterviewPrep {
  return {
    behavioral: [
      {
        question: "Tell me about a time you disagreed with a technical decision.",
        hint: "Use the prototype-not-debate story. Lead with the questions you asked before asserting anything, and be explicit that you offered to support the other design if the numbers had not held up.",
      },
      {
        question: "Describe a project you owned end to end.",
        hint: "The SSR migration is the strongest option: it has scope, a measurable outcome, and evidence you brought a sceptical team along rather than acting alone.",
      },
      {
        question: "Tell me about a time you made a mistake in production.",
        hint: "Pick one with real consequence and be specific about what you changed structurally afterwards, not just what you fixed. A story with no cost reads as evasive.",
      },
    ],
    technical: [
      {
        question: `How would you design the data model for ${job.company}'s core product?`,
        hint: "Clarify access patterns before writing anything down. Say out loud which queries you are optimising for and what you are willing to make slower.",
      },
      {
        question: "Walk me through how you would debug a slow endpoint.",
        hint: "Measure before hypothesising. Name your tools, then talk about distinguishing a slow query from a slow serialisation path from a slow downstream call.",
      },
      {
        question: "How do you enforce a spending limit correctly under concurrency?",
        hint: "Your billing-path story fits exactly. Draw the check-then-act gap, then the atomic conditional update that closes it.",
      },
    ],
    roleSpecific: [
      {
        question: `Why the ${job.role} role specifically, rather than a pure frontend or pure backend one?`,
        hint: "Answer with a concrete preference rather than a claim of flexibility: you want the data model and the interface in the same head because the interesting bugs live between them.",
      },
      {
        question: "How do you decide what to test?",
        hint: "Money paths, permission checks, and anything with a concurrency dimension. Say explicitly that you do not chase a coverage number and why.",
      },
    ],
    cultureFit: [
      {
        question: "How do you handle competing priorities?",
        hint: "Show a decision procedure, not a personality trait. Who you escalate to and how quickly matters more than saying you stay calm.",
      },
      {
        question: "What kind of code review do you like to receive?",
        hint: "Specific and early. Mention that you would rather be told the design is wrong on day one than have the implementation praised on day five.",
      },
    ],
    questionsToAskThem: [
      "What does the first ninety days look like for whoever takes this role?",
      "Where does the current architecture hurt most, and what would you change with a free month?",
      "How do decisions get made when engineering and product disagree?",
      "What does on-call look like, and how often does it actually page?",
      `What would make you say in six months that this ${job.role} hire went really well?`,
    ],
  };
}

// ---------------------------------------------------------------------------
// Outreach
// ---------------------------------------------------------------------------

const OUTREACH_FIXTURES: Record<string, (job: DemoJob) => string> = {
  linkedin_note: (job) =>
    `Hi - I have just applied for the ${job.role} role at ${job.company}. I spent the last few years on metering and data-model work that lines up closely with what the posting describes, and I would welcome the chance to connect.`,

  linkedin_dm: (job) =>
    `Hi,\n\nI applied for the ${job.role} role last week and wanted to introduce myself directly.\n\nThe short version: seven years of full stack work, most recently owning a metered generation pipeline end to end, including the concurrency controls that make spend limits hold under parallel load. The posting's emphasis on end-to-end ownership is what made me apply rather than the stack.\n\nHappy to send more detail if useful, and equally happy if the timing is not right.\n\nBest,\nAlex`,

  followup_email: (job) =>
    `Subject: Following up on the ${job.role} application\n\nHi,\n\nI applied for the ${job.role} role at ${job.company} a couple of weeks ago and wanted to check in briefly in case my application had not surfaced.\n\nSince applying I have been working on exactly the kind of problem the posting describes: closing a concurrency hole in a billing path where the spend check and the charge were separate operations. Happy to walk through it if it is relevant.\n\nStill interested, and I appreciate you taking the time.\n\nBest,\nAlex Morgan`,

  thankyou_email: (job) =>
    `Subject: Thank you\n\nHi,\n\nThank you for the time today. I enjoyed the conversation more than I expected to, particularly the discussion about where the data model is creaking.\n\nOne thing I did not say well: when you asked how I would approach the migration, I jumped to the mechanics. The part I should have led with is that I would want to run both paths in parallel with automated reconciliation before cutting over, because on a path that customers make decisions from, being briefly slow is survivable and being briefly wrong is not.\n\nThanks again. I would be glad to keep talking about the ${job.role} role.\n\nBest,\nAlex`,

  linkedin_followup_dm: (job) =>
    `Hi - following up on my note about the ${job.role} role. I know inboxes are busy, so no problem at all if the timing is not right or the search has moved on. If it would help to see how I think rather than read about it, I am happy to send a short write-up of a recent piece of work. Either way, thanks.`,

  cold_email: (job) =>
    `Subject: Full stack engineer, interested in ${job.company}\n\nHi,\n\nI do not think you have an open ${job.role} posting right now, so this is speculative.\n\nI am a full stack engineer with seven years of experience, most recently at Meridian Labs where I own a metered generation pipeline end to end. The work I am proudest of is a concurrency fix in our billing path: the spend check and the charge were separate operations, so parallel requests all read the same stale total and the limit only held for serial traffic. I reproduced it with a test and closed it with an atomic conditional update.\n\nI am reaching out to ${job.company} specifically because the problems you are working on are close to that. If there is nothing now, I would still value being on your radar.\n\nBest,\nAlex Morgan`,

  checkin_email: (job) =>
    `Subject: Checking in\n\nHi,\n\nIt has been a few weeks since we spoke about the ${job.role} role, so I wanted to check in without being a nuisance.\n\nNothing has changed on my end: still interested, still available. If the role is on hold or has gone to someone else, I would genuinely rather know than keep wondering, and it would not change my view of the conversation we had.\n\nBest,\nAlex`,

  salary_negotiation: (job) =>
    `Subject: ${job.role} offer\n\nHi,\n\nThank you for the offer. I want to say clearly up front that I want to work at ${job.company} and I expect us to land this.\n\nOn compensation: the base is below where I need to be. Based on the level of the role and what I have seen for comparable senior full stack positions, I am looking for a base of $205,000. I have another offer at $195,000 that I am not trying to leverage so much as be transparent about, because I would rather take this role at a fair number than the other one.\n\nIf base is constrained, I am open to discussing the equity or the signing component instead. What I care about is the total landing somewhere defensible.\n\nHappy to talk it through live if that is easier.\n\nBest,\nAlex`,
};

// ---------------------------------------------------------------------------
// Entry points
// ---------------------------------------------------------------------------

export function demoOutreach(type: string, job: DemoJob): string {
  const build = OUTREACH_FIXTURES[type];
  if (build) return `${build(job)}\n\n${DEMO_OUTPUT_NOTE}`;
  return `No demo fixture exists for the "${type}" generator yet.\n\n${DEMO_OUTPUT_NOTE}`;
}

export function demoAnalysis(job: DemoJob): JDAnalysis {
  return demoJDAnalysis(job);
}

export function demoPrep(job: DemoJob): InterviewPrep {
  return demoInterviewPrep(job);
}

/**
 * Builds and persists a demo resume or cover letter. Writing a real Document
 * record keeps the demo honest end to end: the export button downloads a DOCX
 * built by the same pipeline a paying user would hit.
 */
export async function demoStructuredDocument(
  userId: string,
  job: DemoJob,
  type: "resume" | "cover_letter"
): Promise<{ documentId: string; content: string; structuredContent: GeneratedResume | GeneratedCoverLetter }> {
  const structuredContent =
    type === "resume" ? demoResume(job) : demoCoverLetter(job);
  // Note goes on the rendered markdown only. structuredContent stays clean so
  // the exported DOCX and LaTeX carry no demo boilerplate.
  const content = `${generatedDocumentToMarkdown(structuredContent)}\n\n${DEMO_OUTPUT_NOTE}`;

  const saved = await documents.upsert(userId, {
    jobId: job._id,
    type,
    content,
    structuredContent: structuredContent as unknown as Record<string, unknown>,
    aiModel: DEMO_MODEL,
    inputTokens: 0,
    outputTokens: 0,
  });

  return { documentId: saved._id, content, structuredContent };
}

// ---------------------------------------------------------------------------
// Fixtures for the standalone AI routes
//
// These live outside generateForJob(), so each needs its own fixture. The
// metering layer refuses demo calls outright (see assertNotDemoUser), which
// means a route added without a fixture fails loudly rather than billing.
// ---------------------------------------------------------------------------

export type DemoOfferComparison = {
  comparisonTable: Array<{ dimension: string; winner: string; notes: string }>;
  prosAndCons: Record<string, { pros: string[]; cons: string[] }>;
  recommendation: { pick: string; reasoning: string };
  negotiationOpportunities: string[];
};

/** Keyed to the three offers in demo-seed.ts. */
export function demoOfferComparison(
  companies: string[]
): DemoOfferComparison {
  const [a = "PlanetScale", b = "Fly.io", c = "Datadog"] = companies;

  return {
    comparisonTable: [
      { dimension: "Base salary", winner: c, notes: `${c} leads at $195k, ${a} $185k, ${b} $170k. A $25k spread.` },
      { dimension: "Equity", winner: a, notes: `${a}'s 0.08% carries the most upside but the most risk. ${c}'s RSUs are liquid today.` },
      { dimension: "Bonus", winner: c, notes: `15% target at ${c}, 10% at ${a}, none at ${b}.` },
      { dimension: "Leave", winner: b, notes: `${b} gives 25 days, ${a} 20, ${c} 15. Ten days is two working weeks.` },
      { dimension: "Flexibility", winner: b, notes: `${a} and ${b} are fully remote. ${c} is three days onsite in New York.` },
      { dimension: "Total first-year cash", winner: c, notes: `Roughly $224k at ${c}, $204k at ${a}, $170k at ${b}.` },
    ],
    prosAndCons: {
      [a]: {
        pros: ["Strongest equity position of the three", "Fully remote", "Infrastructure work with real depth"],
        cons: ["Earlier stage, so the equity is the least certain", "Mid-range base"],
      },
      [b]: {
        pros: ["Most leave by a clear margin", "Fully remote", "Highest autonomy"],
        cons: ["Lowest base by $15k", "No bonus at all", "Smallest equity grant"],
      },
      [c]: {
        pros: ["Highest base and total cash", "Liquid RSUs, not paper", "Established company"],
        cons: ["Three days onsite in New York", "Least leave", "Largest team, so less individual scope"],
      },
    },
    recommendation: {
      pick: a,
      reasoning: `On cash alone ${c} wins, but the gap is roughly $20k a year against a three-day onsite requirement and ten fewer days of leave. If you are optimising for the next twelve months, take ${c}. If you are optimising for the next four years, ${a} pairs the best equity with full remote and the base is close enough that the difference is negotiable. ${b} only wins if leave and autonomy outrank everything else, because the cash gap is real.`,
    },
    negotiationOpportunities: [
      `${a}'s base has the most room. You hold a $195k offer, so $195k at ${a} is a reasonable and evidenced ask.`,
      `${c} is unlikely to move much on base, but sign-on bonuses are usually the flexible component at that size.`,
      `${b}'s equity grant is small enough that a meaningful increase costs them little. Ask there rather than on base.`,
      `Every one of these has an expiry. Ask for an extension in writing before you start negotiating, not after.`,
    ],
  };
}

export type DemoSkillsGap = {
  summary: string;
  highPriority: Array<{ skill: string; why: string; howToLearn: string; timeEstimate: string }>;
  mediumPriority: Array<{ skill: string; why: string; howToLearn: string; timeEstimate: string }>;
  lowPriority: Array<{ skill: string; why: string; howToLearn: string; timeEstimate: string }>;
  quickWins: string[];
};

export function demoSkillsGap(): DemoSkillsGap {
  return {
    summary:
      "Across the job descriptions you have analysed, your TypeScript, React and data-modelling experience covers the large majority of stated requirements. The consistent gaps are Python (named in roughly a third of the roles), Kubernetes, and explicit distributed-systems depth. None are disqualifying for a product-facing full stack role, but Python appears often enough to be worth closing rather than explaining away.",
    highPriority: [
      {
        skill: "Python",
        why: "Named in about a third of the roles you saved, usually as the backend alongside a TypeScript frontend. You have shipped it, but not recently enough to speak fluently about it under pressure.",
        howToLearn: "Port one existing Node service to FastAPI. You already know the domain, so the effort goes into the language and its idioms rather than the problem.",
        timeEstimate: "2 to 3 weeks part time",
      },
      {
        skill: "Distributed systems vocabulary",
        why: "Several senior postings ask for it explicitly, and the system-design round assumes it. Your metering and reconciliation work already demonstrates the thinking; what is missing is the shared language for it.",
        howToLearn: "Work through Designing Data-Intensive Applications chapters 5 to 9, then write up your billing concurrency fix in those terms. You solved the problem already.",
        timeEstimate: "4 to 6 weeks",
      },
    ],
    mediumPriority: [
      {
        skill: "Kubernetes",
        why: "Appears in the infrastructure-leaning roles but rarely as a hard requirement for product engineering. Worth enough to not be a blank.",
        howToLearn: "Deploy one of your own projects to a managed cluster end to end. Depth beyond that has poor returns for the roles you are targeting.",
        timeEstimate: "1 to 2 weeks",
      },
      {
        skill: "Go",
        why: "Shows up in the infrastructure companies you have saved, particularly the database and platform ones.",
        howToLearn: "Build one small CLI tool. Enough to read the language confidently and say honestly that you have written some.",
        timeEstimate: "2 weeks",
      },
    ],
    lowPriority: [
      {
        skill: "GraphQL",
        why: "Named in only one saved role, and REST is stated more often. Low return on the time.",
        howToLearn: "Read the spec overview and be able to discuss the trade-off against REST. Do not build anything.",
        timeEstimate: "2 days",
      },
      {
        skill: "Rust",
        why: "Nice signal for the systems companies, but none of your saved roles require it and the learning curve is steep.",
        howToLearn: "Defer this until a specific role justifies it.",
        timeEstimate: "Not now",
      },
    ],
    quickWins: [
      "Add Python to your resume skills line. You have shipped it; leaving it off reads as not having it at all.",
      "Rewrite your billing concurrency fix in distributed-systems terms. It is your strongest story and it is currently described in application language.",
      "Put explicit numbers on the SSR migration in every version of your resume. 4.1s to 1.3s is more persuasive than the project's scope.",
      "Deploy one project to a managed Kubernetes cluster this weekend, purely to remove the blank.",
    ],
  };
}

/** Polished STAR output, tailored to whatever the story is called. */
export function demoPolishedStory(title: string): string {
  return `**Situation**
${title}. The context that mattered: the problem was visible to people outside the team, it had persisted long enough that it was being treated as normal, and the obvious fix would have taken longer than anyone was willing to wait.

**Task**
I took ownership of it. The constraint I set myself was that whatever I did had to be reversible, because the system was load-bearing and I was not confident enough in my understanding to make a one-way change.

**Action**
I started by measuring rather than theorising, which contradicted my first instinct about the cause. Once I had numbers I built the smallest change that would prove or disprove the hypothesis, put it behind a flag, and ran it alongside the existing path with automated comparison between the two. When the results agreed for long enough to be convincing, I cut over. I wrote up the failure mode afterwards so the next person would not rediscover it.

**Result**
The measured outcome held: the problem went away and did not come back, and the comparison job caught two issues during the parallel period that would otherwise have reached users. What I would do differently is measure sooner. I spent the first two days on a theory that the data disproved in an hour.

---
${DEMO_OUTPUT_NOTE}`;
}

export type DemoParsedJob = {
  company: string | null;
  role: string | null;
  location: string | null;
  salary: string | null;
  description: string | null;
};

export function demoParsedJob(): DemoParsedJob {
  return {
    company: "Example Corp",
    role: "Senior Full Stack Engineer",
    location: "Remote (US)",
    salary: "$180k - $215k",
    description:
      "This is demo output. Quick import normally sends your pasted job posting to Claude, which extracts the company, role, location, salary and a cleaned-up description. The demo account returns this fixed example instead, so nothing you paste is sent anywhere. Sign up with your own account to parse real postings.",
  };
}
